// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightLinksValidator from 'starlight-links-validator';
import { existsSync } from 'node:fs';

// scripts/import-api.mjs (prebuild/predev) has already run when Astro loads this file.
const apiGenerated = existsSync('./src/content/docs/plugins/api/lua.md');

export default defineConfig({
  site: 'https://docs.nodemp.com',
  // Slugs removed by the phase-4 rewrite. Astro emits a meta-refresh page for each.
  redirects: {
    '/introduction/beammp-compatibility/': '/introduction/differences-from-beammp/',
    '/ru/introduction/beammp-compatibility/': '/ru/introduction/differences-from-beammp/',
    '/plugins/server-api/': '/plugins/api/lua/',
    '/ru/plugins/server-api/': '/ru/plugins/api/lua/',
    '/plugins/client-api/': '/plugins/client-scripting/',
    '/ru/plugins/client-api/': '/ru/plugins/client-scripting/',
    // The section root has no page of its own; readers type it.
    '/plugins/': '/plugins/overview/',
    '/ru/plugins/': '/ru/plugins/overview/',
  },
  integrations: [
    starlight({
      title: 'NodeMP',
      logo: { src: './src/assets/nmp-logo.png', alt: 'NodeMP' },
      customCss: ['./src/styles/custom.css'],
      plugins: [starlightLinksValidator({
        errorOnRelativeLinks: true,
        errorOnFallbackPages: false,
        // Without the sdk only the placeholder /plugins/api/ exists: skip links into the generated pages.
        exclude: apiGenerated ? [] : ['/plugins/api/**', '/ru/plugins/api/**'],
      })],
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/NodeMP-BeamNG' },
      ],
      defaultLocale: 'root',
      locales: {
        root: { label: 'English', lang: 'en' },
        ru: { label: 'Русский', lang: 'ru' },
      },
      // Item labels come from the page titles (slug entries), so the RU sidebar
      // shows the RU titles without a second list of labels here.
      sidebar: [
        { label: 'Introduction', translations: { ru: 'Введение' }, items: [
          { slug: 'introduction/what-is-nodemp' },
          { slug: 'introduction/differences-from-beammp' },
        ]},
        { label: 'Framework', translations: { ru: 'Фреймворк' }, items: [
          { slug: 'framework/overview' },
          { slug: 'framework/sync' },
        ]},
        { label: 'For players', translations: { ru: 'Игрокам' }, items: [
          { slug: 'players/install' },
          { slug: 'players/join' },
          { slug: 'players/settings' },
          { slug: 'players/troubleshooting' },
        ]},
        { label: 'Server hosting', translations: { ru: 'Хостинг сервера' }, items: [
          { slug: 'hosting/quick-start' },
          { slug: 'hosting/configuration' },
          { slug: 'hosting/strict-verification' },
          { slug: 'hosting/running' },
          { slug: 'hosting/registering' },
          { slug: 'hosting/updating' },
          { slug: 'hosting/resources' },
        ]},
        { label: 'Plugin development', translations: { ru: 'Разработка плагинов' }, items: [
          { slug: 'plugins/overview' },
          { slug: 'plugins/getting-started' },
          { slug: 'plugins/resources' },
          { slug: 'plugins/events' },
          { slug: 'plugins/concurrency' },
          { slug: 'plugins/database' },
          { slug: 'plugins/client-scripting' },
          { slug: 'plugins/native-modules' },
          { slug: 'plugins/recipes' },
          { slug: 'plugins/conventions' },
          { slug: 'plugins/protocol' },
          // Label override: the page title names BeamMP; the global navigation does not.
          { slug: 'plugins/migrating', label: 'Migrating plugins', translations: { ru: 'Перенос плагинов' } },
          // Generated by scripts/import-api.mjs from sdk/api.toml; never edited by hand.
          { label: 'API reference', translations: { ru: 'Справочник API' }, items: [{ autogenerate: { directory: 'plugins/api' } }] },
        ]},
        { label: 'Reference', translations: { ru: 'Справочник' }, items: [
          { slug: 'reference/faq' },
          { slug: 'reference/error-codes' },
          { slug: 'reference/glossary' },
        ]},
      ],
    }),
  ],
});
