// Check 6: plugins/protocol.md against server/run/wire_taxonomy.py (generated by
// sdk/tools/wiregen.py from include/net/Protocol.h): the protocol version, the
// category table (name, byte), and per category the subtype rows -- their set
// and order (which is the id), the heading count, the direction and channel,
// explicit `0xNN` ids and `type field` body tokens quoted in the purpose column,
// and the size limits paragraph.
import { tables, codeLineSet } from './md.mjs';
import { snake } from './sources.mjs';

const finding = (check, page, line, claim, expected, actual) => ({ check, page: page.path, locale: page.locale, line, claim, expected, actual });

// "L→S, T and U" / "G↔S, U with T fallback" / "G→S" -> { dir: 'L->S', channel: 'T,U' | 'U(T)' | null }
export function parseDirection(cell) {
  let s = cell.replace(/`/g, '').replace(/→/g, '->').replace(/↔/g, '<->').trim();
  s = s.replace(/\bU (?:with T fallback|с откатом на T)\b/i, 'U(T)').replace(/\s+(?:and|и)\s+/g, ',');
  const comma = s.indexOf(',');
  const dir = comma < 0 ? s : s.slice(0, comma);
  const channel = comma < 0 ? null : s.slice(comma + 1);
  return { dir: dir.replace(/\s+/g, '') || null, channel: channel ? channel.replace(/\s+/g, '') : null };
}

const num = (s) => Number(s.replace(/`/g, '').trim());

export function checkProtocolPage(page, wire) {
  const out = [];
  const text = page.text;
  const lines = text.split(/\r?\n/);
  const code = codeLineSet(text);
  // (The protocol version itself is a versions.json claim -- see versions.mjs.)

  const tbls = tables(text);
  // The category table: rows `Name` | `0xNN` | ...
  const cat = tbls.find((t) => t.rows.length && t.rows.every((r) => /^`0x[0-9A-Fa-f]{2}`$/.test(r.cells[1] || '')));
  if (cat) {
    const seen = new Set();
    for (const r of cat.rows) {
      const name = r.cells[0].replace(/`/g, '');
      const c = wire.categories.find((x) => x.name === name);
      if (!c) { out.push(finding('protocol.category', page, r.line, name, 'a Category of Protocol.h', 'unknown')); continue; }
      seen.add(name);
      if (num(r.cells[1]) !== c.byte) out.push(finding('protocol.category', page, r.line, `${name} byte`, hex(c.byte), r.cells[1].replace(/`/g, '')));
    }
    for (const c of wire.categories) if (!seen.has(c.name)) out.push(finding('protocol.category', page, cat.start, c.name, `a row for ${c.name} (${hex(c.byte)})`, 'missing'));
    // "Eight categories exist" / "Существует восемь категорий".
    for (let i = 0; i < lines.length; i++) {
      if (code.has(i + 1)) continue;
      const m = /([\p{L}\d]+)\s+(?:categories|категори[йия])\b/iu.exec(lines[i]);
      const n = m && wordNumber(m[1]);
      if (n != null && n !== wire.categories.length) out.push(finding('protocol.category', page, i + 1, m[0], `${wire.categories.length} categories`, m[0]));
    }
  }

  // Per-category tables: the heading `### Name (N)` right above.
  for (const t of tbls) {
    if (t === cat) continue;
    let h = t.start - 2;
    while (h >= 0 && !/^###\s/.test(lines[h])) h--;
    const hm = h >= 0 && /^###\s+(\w+)\s*\((\d+)\)/.exec(lines[h]);
    if (!hm) continue;
    const category = hm[1];
    const packets = wire.packets[category];
    if (!packets) { out.push(finding('protocol.table', page, h + 1, category, 'a Category of Protocol.h', 'unknown')); continue; }
    if (Number(hm[2]) !== packets.length) out.push(finding('protocol.table', page, h + 1, `${category} (${hm[2]})`, `${category} (${packets.length})`, `${category} (${hm[2]})`));
    const names = t.rows.map((r) => r.cells[0].replace(/`/g, '').trim());
    t.rows.forEach((r, idx) => {
      const name = names[idx];
      const p = packets.find((x) => x.name === name || x.snake === snake(name));
      if (!p) { out.push(finding('protocol.table', page, r.line, `${category}::${name}`, 'a subtype of Protocol.h', 'unknown')); return; }
      // Row order is the subtype id.
      if (p.id !== idx + 1) out.push(finding('protocol.table', page, r.line, `${category}::${name} position`, `row ${p.id} (subtype ${hex(p.id)})`, `row ${idx + 1}`));
      const d = parseDirection(r.cells[1] || '');
      if (p.dir && d.dir !== p.dir) out.push(finding('protocol.table', page, r.line, `${category}::${name} direction`, p.dir, d.dir ?? '(none)'));
      if (p.channel && d.channel && d.channel !== p.channel) out.push(finding('protocol.table', page, r.line, `${category}::${name} channel`, p.channel, d.channel));
      const purpose = r.cells[2] || '';
      if (!/moved|from|перенес|из /i.test(purpose)) {
        for (const m of purpose.matchAll(/`(0x[0-9A-Fa-f]{2})`/g)) {
          if (parseInt(m[1], 16) !== p.id) out.push(finding('protocol.table', page, r.line, `${category}::${name} id`, hex(p.id), m[1]));
        }
      }
      // Body tokens quoted as `u8 level` / `tail:str manifest_hash` / `u32 index, u32 total, ...`
      for (const m of purpose.matchAll(/`((?:(?:u8|u16|u32|u64|i8|i32|f32|str16|tail:\w+)\s+\w+)(?:,\s*(?:u8|u16|u32|u64|i8|i32|f32|str16|tail:\w+)\s+\w+)*)`/g)) {
        for (const tok of m[1].split(/,\s*/)) {
          if (!p.body.includes(tok)) out.push(finding('protocol.table', page, r.line, `${category}::${name} body`, p.body || '(no body)', tok));
        }
      }
    });
    for (const p of packets) if (!names.some((n) => n === p.name || snake(n) === p.snake)) out.push(finding('protocol.table', page, t.start, `${category}::${p.name}`, `a row (subtype ${hex(p.id)}, ${p.dir ?? ''} ${p.channel ?? ''})`, 'missing'));
  }

  // Limits: the numbers in the "Limits" bullet.
  const limits = lines.findIndex((l) => /^\s*-\s*\*\*(Limits|Лимиты|Ограничения)/.test(l));
  if (limits >= 0) {
    let para = lines[limits];
    for (let j = limits + 1; j < lines.length && /^\s{2,}\S/.test(lines[j]); j++) para += ' ' + lines[j];
    const c = wire.constants;
    const expectations = [
      [/(\d+)\s*(?:KB|КБ|KiB|КиБ)\s+(?:before|до)\s+`Welcome`/, c.PRE_AUTH_FRAME_CAP / 1024, 'PRE_AUTH_FRAME_CAP'],
      [/(\d+)\s*(?:MB|МБ)\s+(?:after|после)/, c.MAX_FRAME_LENGTH / (1024 * 1024), 'MAX_FRAME_LENGTH'],
      [/(?:datagram|датаграмм\w*)\s+(?:at|в|-)\s+(\d+)\s*(?:KB|КБ)/, c.MAX_UDP_DATAGRAM / 1024, 'MAX_UDP_DATAGRAM'],
      [/(?:config|конфигурац\w+)\D{0,20}(\d+)\s*(?:KB|КБ)/, c.MAX_VEHICLE_CONFIG_JSON / 1024, 'MAX_VEHICLE_CONFIG_JSON'],
      [/`IntegrityChunkBytes`\s*=\s*(\d+)\s*(?:KiB|КиБ)/, c.INTEGRITY_CHUNK_BYTES / 1024, 'INTEGRITY_CHUNK_BYTES'],
    ];
    for (const [re, want, name] of expectations) {
      const m = re.exec(para);
      if (m && Number.isFinite(want) && Number(m[1]) !== want) out.push(finding('protocol.limits', page, limits + 1, m[0], `${want} (${name})`, m[1]));
    }
  }
  return out;
}

const hex = (n) => '0x' + n.toString(16).toUpperCase().padStart(2, '0');

const WORDS = { one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7, eight: 8, nine: 9, ten: 10, восемь: 8, семь: 7, девять: 9, шесть: 6, пять: 5, десять: 10 };
function wordNumber(w) {
  if (/^\d+$/.test(w)) return Number(w);
  return WORDS[w.toLowerCase()] ?? null;
}

export function checkProtocol(pages, sources) {
  const out = [];
  if (!sources.wire) return out;
  for (const page of pages) if (/^plugins\/protocol\.mdx?$/.test(page.slug)) out.push(...checkProtocolPage(page, sources.wire));
  return out;
}
